### ISSUE TITLE
Inability to read current configuration values from ConnectX-3 EN NICs causes panic

### ISSUE THREAD

**Issue by KingJ** [openshift/sriov-network-operator#666]
Hi there,

I'm trying to use the operator to configure SR-IOV on a few machines that use older ConnectX-3 EN NICs (e.g. MCX312A-XCB_A2-A6). It appears that it isn't possible to read the current configuration values from these cards, even on the latest firmware (2.42.5000). When run in verbose mode, `mst-config` emits a `Device Firmware does not support reading current configurations` warning at the end of the configuration parameter output.

This means that the output of `mstconfig -e` will return just 3 columns, the configuration attribute name, default value and the next boot value. However, the operator assumes that the output of `mstconfig` has 4 columns, and as a 4th column is missing [parseMstConfigOutput](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/4af837211ed61f20890a9968d5b712b74893fc87/pkg/plugins/mellanox/mellanox_plugin.go#L273)'s regex will trigger an index out of range error when it attempts to [read the 4th index of a match](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/4af837211ed61f20890a9968d5b712b74893fc87/pkg/plugins/mellanox/mellanox_plugin.go#L284) (i.e. the `Next` regex capture group).

I've included a stacktrace below, which also includes the 3-column output from `mstconfig -e`. I have a feeling this won't be an easy one to work around given the operator needs to be able to know the current configuration parameters in order to change them if they're wrong. Equally, i'm unsure if it is even worth working around given the age of these NICs and their lack of formal support on this project! Nonetheless, I thought it best to raise an issue just in case there is a reasonably simple workaround, or if someone else hits this in the future.

```
I0515 11:13:19.787203 3220570 mellanox_plugin.go:231] mellanox-plugin getMlnxNicFwData(): device 0000:02:00.0
I0515 11:13:19.787213 3220570 mellanox_plugin.go:224] mellanox-plugin mstConfigReadData(): device 0000:02:00.0
I0515 11:13:19.787217 3220570 utils.go:740] RunCommand(): mstconfig [-e -d 0000:02:00.0 q]
I0515 11:13:19.787274 3220570 utils.go:747] RunCommand(): mstconfig, [-e -d 0000:02:00.0 q]
I0515 11:13:21.482606 3220570 utils.go:749] RunCommand(): 
Device #1:
----------

Device type:    ConnectX3       
Device:         0000:02:00.0    

Configurations:                              Default         Next Boot
*        SRIOV_EN                            False(0)        True(1)         
         NUM_OF_VFS                          8               8               
         LOG_BAR_SIZE                        3               3               
         BOOT_OPTION_ROM_EN_P1               True(1)         True(1)         
         BOOT_VLAN_EN_P1                     False(0)        False(0)        
         BOOT_RETRY_CNT_P1                   0               0               
         LEGACY_BOOT_PROTOCOL_P1             PXE(1)          PXE(1)          
         BOOT_VLAN_P1                        1               1               
         BOOT_OPTION_ROM_EN_P2               True(1)         True(1)         
         BOOT_VLAN_EN_P2                     False(0)        False(0)        
         BOOT_RETRY_CNT_P2                   0               0               
         LEGACY_BOOT_PROTOCOL_P2             PXE(1)          PXE(1)          
         BOOT_VLAN_P2                        1               1               
         IP_VER_P1                           IPv4(0)         IPv4(0)         
         IP_VER_P2                           IPv4(0)         IPv4(0)         
         CQ_TIMESTAMP                        True(1)         True(1)         
The '*' shows parameters with next value different from default/current value.
Device Firmware does not support reading current configurations
, %!s(<nil>)
I0515 11:13:21.482636 3220570 mellanox_plugin.go:274] mellanox-plugin parseMstconfigOutput(): Attributes [NUM_OF_VFS SRIOV_EN LINK_TYPE_P1 LINK_TYPE_P2]
E0515 11:13:21.482816 3220570 runtime.go:78] Observed a panic: runtime.boundsError{x:3, y:0, signed:true, code:0x0} (runtime error: index out of range [3] with length 0)
goroutine 78 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1f97aa0, 0xc00109a288})
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2fcb548})
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1f97aa0, 0xc00109a288})
	/usr/local/go/src/runtime/panic.go:1038 +0x229
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/plugins/mellanox.parseMstconfigOutput({0xc00115f500, 0x611}, {0xc001430d80, 0x4, 0xc000aaf448})
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/plugins/mellanox/mellanox_plugin.go:283 +0x34a
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/plugins/mellanox.getMlnxNicFwData({0xc001148610, 0xc})
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/plugins/mellanox/mellanox_plugin.go:240 +0x189
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/plugins/mellanox.(*MellanoxPlugin).OnNodeStateChange(0x1dfb880, 0xc0004f9708, 0xc000170d80)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/plugins/mellanox/mellanox_plugin.go:163 +0x785
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/plugins/mellanox.(*MellanoxPlugin).OnNodeStateAdd(0xc0003d0180, 0x0)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/plugins/mellanox/mellanox_plugin.go:66 +0x6c
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon.(*Daemon).nodeStateSyncHandler(0xc0003d0180, 0xc00045b260)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon/daemon.go:442 +0x506
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon.(*Daemon).processNextWorkItem.func1(0xc0003d0180, {0x1df7e00, 0x2fcb548})
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon/daemon.go:332 +0x106
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon.(*Daemon).processNextWorkItem(0xc0003d0180)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon/daemon.go:348 +0x165
github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon.(*Daemon).runWorker(...)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon/daemon.go:293
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f46043fa7e8)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000493380, {0x22ab340, 0xc0008c6060}, 0x1, 0xc0002220c0)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000f8d260, 0x3b9aca00, 0x0, 0x80, 0xbf5ea5)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x10aa5ea, 0xc000376000, 0xc000493380)
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon.(*Daemon).Run
	/go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/pkg/daemon/daemon.go:268 +0xa9f
panic: runtime error: index out of range [3] with length 0 [recovered]
	panic: runtime error: index out of range [3] with length 0
```

**Comment by SchSeba** [comment]
Hi @KingJ please check I think the mlx CX3 is not supported by the operator only 4+

https://github.com/openshift/sriov-network-operator/blob/master/deploy/configmap.yaml
